SET search_path TO EMISSORA;

SELECT * FROM CLIENTE;

SELECT COUNT(CLIENTE.CODCLI)
FROM CLIENTE, ASSINAM, CANALASSINATURA, SERVICOSCANALTV
WHERE CLIENTE.CODCLI = ASSINAM.CODCLI AND CANALASSINATURA.NUMCANAL = ASSINAM.NUMCANAL
AND CANALASSINATURA.NUMCANAL = SERVICOSCANALTV.NUMCANAL
GROUP BY SERVICOSCANALTV.NOMECANAL;

SELECT * FROM FUNCIONARIO;

SELECT * FROM FUNCIONARIO F,TECNICOS T
	WHERE F.CODFUNC = T.CODFUNC;

SELECT * FROM FUNCIONARIO F,PRODUTORES_DIRETORES P
	WHERE F.CODFUNC = P.CODFUNC;

SELECT * FROM FUNCIONARIO F,GESTORESADMINISTRATIVOS G
	WHERE F.CODFUNC = G.CODFUNC;


SELECT * FROM DEPENDENTES;

SELECT F.CODFUNC,F.NOME,D.NOME
FROM FUNCIONARIO F,DEPENDENTES D
WHERE F.CODFUNC = D.CODFUNC;



SELECT * FROM DEPARTAMENTOS;

SELECT D.NOMEDEP, COUNT(F.CODFUNC)
FROM DEPARTAMENTOS D, FUNCIONARIO F,TRABALHAM T
WHERE  F.CODFUNC = T.CODFUNC AND D.CODDEP = T.CODDEP
GROUP BY D.NOMEDEP

SELECT AVG(FUNCIONARIO.SALARIO)
FROM FUNCIONARIO
